language:
    - cpp

git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --remote --recursive
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-avr binutils-avr avr-libc

script:
    - ./build.sh build

notifications:
    email: false
