language:
    - cpp

git:
    submodules: false

before_install:
    - git submodule update --init --remote --recursive
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-avr binutils-avr avr-libc


notifications:
    email: false
